### ISSUE TITLE
Issue with version check

### ISSUE THREAD

**Issue by voltageek** [Mgamerz/me3modmanager#20]
The application fails with a message saying that "This application requires java runtime environment 1.8.0_30" even though I have 1.8.0_101 installed. Looks like it's related to a launch4j bug ([https://sourceforge.net/p/launch4j/bugs/146/](https://sourceforge.net/p/launch4j/bugs/146/)) where version checks fail if the version is greater than 99.  Looks like a fix for the launch4j issue has been put in place

**Comment by Mgamerz** [comment]
I have seen a few issues of this come up. I will push out a fix ASAP since
this will probably kill my userbase, thanks java.

**Comment by Mgamerz** [comment]
Fixed in https://github.com/Mgamerz/me3modmanager/releases/tag/4.2.5r1

Thanks for reporting the issue.
