### ISSUE TITLE
Modmanager not starting - not detecting .net framework 4.7 on Win10 x64 Creators update

### ISSUE THREAD

**Issue by Shtoomik** [Mgamerz/me3modmanager#52]
Log attached 

[me3cmm_last_run_log.txt](https://github.com/Mgamerz/me3modmanager/files/1176888/me3cmm_last_run_log.txt)

**Comment by Mgamerz** [comment]
Interesting. Never seen this before. 

I will update the wrapper to include nosys and we will see if that fixes it.

**Comment by Mgamerz** [comment]
Fixed by updating the wrapper settings.

-Djna.nosys=true in the JRE/Environment Variables area.
